### ISSUE TITLE
ios模拟器登陆失败

### ISSUE THREAD

**Issue by DrMatioDevelop** [CarGuo/GSYGithubAppWeex#18]
由于CocoaPods的原因 我修改了 
`	pod 'WeexSDK', :git => 'https://github.com/CarGuo/incubator-weex.git', :branch => '0.18.0.2_web'
`
变为
`pod 'WeexSDK‘, '=0.18.0'` 
能到登陆界面，但是输入用户名密码 转个圈之后没有任何反应 ，没有其他toast提示，控制台也没有消息

**Comment by DrMatioDevelop** [comment]
然后想看下是不是网页报错  npm run dev
`npm run serve

> gsy-github-weex-app@1.0.0 serve /Users/cyf/Desktop/GSYGithubAppWeex-master
> webpack-dev-server --env.NODE_ENV=development --progress

TypeError: Cannot destructure property `compile` of 'undefined' or 'null'.
    at addHooks (/Users/cyf/Desktop/GSYGithubAppWeex-master/node_modules/webpack-dev-server/lib/Server.js:114:49)
    at new Server (/Users/cyf/Desktop/GSYGithubAppWeex-master/node_modules/webpack-dev-server/lib/Server.js:127:5)
    at startDevServer (/Users/cyf/Desktop/GSYGithubAppWeex-master/node_modules/webpack-dev-server/bin/webpack-dev-server.js:355:14)
    at processOptions (/Users/cyf/Desktop/GSYGithubAppWeex-master/node_modules/webpack-dev-server/bin/webpack-dev-server.js:309:5)
    at internalTickCallback (internal/process/next_tick.js:77:7)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:778:11)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)`

**Comment by CarGuo** [comment]
weex这里没做错误提示，你可以看看是不是因为github api id和sercet不对，导致的401或者422

**Comment by DrMatioDevelop** [comment]
首先感谢郭大喵的老板的及时回复；
问题是自己没睁开眼睛看清楚😳，
1️⃣要先注册[https://github.com/settings/applications/new](url)，
2️⃣拿到对应的client_id 与 client_secret 
3️⃣在你需要自己项目src/core/common/目录下 创建一个ignoreConfig.js文件，然后输入你申请的Github client_id 和 client_secret
4️⃣运行项目后，显示登陆界面后， 使用自己的github账号密码登陆   **配置文件（ignoreConfig.js）的client_id与client_secret不是github的账号密码是第一步注册的  切记切记**

另外项目运行白屏的如果是ios  请修改 `platforms⁩/⁨ios/podfile⁩`   ` pod 'WeexSDK‘, '=0.18.0'`, 因为本人使用最新的weexSDK（0.19.0）也会白屏
